name: qrcode_maker
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  #google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  
  image_path: "images/logo.jpg"

  
flutter:

  
  uses-material-design: true

  
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  
  # example:
  fonts:
    - family: Digital
      fonts:
        - asset: fonts/DigitalNormal-xO6j.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
